repos:
  - repo: https://github.com/krzysztofzablocki/Sourcery
    rev: 2.0.2
    hooks:
      - id: sourcery
        args: [--quiet]
        stages: [pre-commit]

  - repo: https://github.com/realm/SwiftLint
    rev: 0.57.0
    hooks:
      - id: swiftlint
        args: [--quiet]

  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.58.5
    hooks:
      - id: swiftformat
        args: [--quiet]
